### ISSUE TITLE
Broken link in section 

### ISSUE THREAD

**Issue by AnimusXCASH** [stellar/new-docs#248]
In section [How to issue an asset](https://developers.stellar.org/docs/issuing-assets/how-to-issue-an-asset/) there is a broken url (404) error on *[how to lock account](https://developers.stellar.org/docs/issuing-assets/limit-asset-supply/)

**Comment by rice2000** [comment]
We ended up pulling that section out of the docs since locking an account isn't really best practice at this point, and showing people how to do it has proved problematic.  For instance, several people have locked an account before setting a home domain, and have been unpleasantly surprised to find out they have to start the process of issuing an asset all over.

See:
https://github.com/stellar/new-docs/pull/259
